version: '3.9'
services:
  mssqldb:
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - 1433:1433
    volumes:
      - ./static:/var/opt/mssql
    environment:
      - SA_PASSWORD=deV0ps@#!
      - ACCEPT_EULA=Y
    networks:
      - mssqldb
    restart: unless-stopped

volumes:
  mssqldb:
    driver: local
    name: mssqldb

networks:
  mssqldb:
