version: '3.8'

services:
  mongodb_1:
    container_name: mongodb_1
    image: mongo:4.4
    volumes:
      - ./mongodb/data_1:/data/db
      - ./script.sh:/scripts/script.sh
    networks:
      - mongodb-network
    ports:
      - 27017:27017
    links:
      - mongodb_2
      - mongodb_3
    restart: always
    entrypoint: ["/usr/bin/mongod", "--port", "27017", "--bind_ip_all", "--replSet", "dbrs"]
  mongodb_2:
    container_name: mongodb_2
    image: mongo:4.4
    volumes:
      - ./mongodb/data_2:/data/db
    networks:
      - mongodb-network
    ports:
      - 27018:27018
    restart: always
    entrypoint: ["/usr/bin/mongod", "--port", "27018", "--bind_ip_all", "--replSet", "dbrs"]
  mongodb_3:
    container_name: mongodb_3
    image: mongo:4.4
    volumes:
      - ./mongodb/data_3:/data/db
    networks:
      - mongodb-network
    ports:
      - 27019:27019
    restart: always
    entrypoint: ["/usr/bin/mongod", "--port", "27019", "--bind_ip_all", "--replSet", "dbrs"]

networks:
  mongodb-network:
