version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.7
    ports:
      - 6603:3306
    volumes:
      - ./static:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=deV0ps@#!
      - MYSQL_PASSWORD=deV0ps@#!
      - MYSQL_USER=jarvis
    networks:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    name: mariadb

networks:
  mariadb:
